// <auto-generated />
using MVC_Database.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220217062740_2")]
    partial class _2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MVC_Database.Models.City", b =>
                {
                    b.Property<string>("CityId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CountryId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("City");

                    b.HasData(
                        new
                        {
                            CityId = "Fröölunda",
                            CountryId = "Sweden"
                        },
                        new
                        {
                            CityId = "Berlin",
                            CountryId = "Germany"
                        });
                });

            modelBuilder.Entity("MVC_Database.Models.Country", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Name");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Name = "Sweden"
                        },
                        new
                        {
                            Name = "Germany"
                        });
                });

            modelBuilder.Entity("MVC_Database.Models.Language", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Name");

                    b.ToTable("Languge");

                    b.HasData(
                        new
                        {
                            Name = "Svenska"
                        },
                        new
                        {
                            Name = "Tyska"
                        });
                });

            modelBuilder.Entity("MVC_Database.Models.LanguagePerson", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("LanguageId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("PersonId", "LanguageId");

                    b.HasIndex("LanguageId");

                    b.ToTable("LangugePerson");
                });

            modelBuilder.Entity("MVC_Database.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CityId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tele")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = "Fröölunda",
                            Name = "Piff",
                            Tele = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            CityId = "Berlin",
                            Name = "puff",
                            Tele = "1234567890"
                        },
                        new
                        {
                            Id = 3,
                            CityId = "Berlin",
                            Name = "Soet gullan",
                            Tele = "12345678190"
                        });
                });

            modelBuilder.Entity("MVC_Database.Models.City", b =>
                {
                    b.HasOne("MVC_Database.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("MVC_Database.Models.LanguagePerson", b =>
                {
                    b.HasOne("MVC_Database.Models.Language", "Language")
                        .WithMany("LanguagePersons")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MVC_Database.Models.Person", "Person")
                        .WithMany("LanguagePersons")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("MVC_Database.Models.Person", b =>
                {
                    b.HasOne("MVC_Database.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId");

                    b.Navigation("City");
                });

            modelBuilder.Entity("MVC_Database.Models.Language", b =>
                {
                    b.Navigation("LanguagePersons");
                });

            modelBuilder.Entity("MVC_Database.Models.Person", b =>
                {
                    b.Navigation("LanguagePersons");
                });
#pragma warning restore 612, 618
        }
    }
}
